# Generated by Django 5.0.6 on 2024-06-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_commentsview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='commentsView',
            new_name='Comments',
        ),
    ]
